version: 2
updates:
  # Monitor npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    reviewers:
      - "alimobrem"
    # Group minor and patch updates to reduce PR noise
    groups:
      # Production dependencies
      production-dependencies:
        patterns:
          - "@openshift-console/*"
          - "@patternfly/*"
          - "react*"
          - "i18next*"
        update-types:
          - "minor"
          - "patch"
      # Development dependencies  
      development-dependencies:
        patterns:
          - "@types/*"
          - "@typescript-eslint/*"
          - "eslint*"
          - "prettier*"
          - "jest*"
          - "cypress*"
          - "webpack*"
          - "typescript"
        update-types:
          - "minor"
          - "patch"
      # Testing dependencies
      testing-dependencies:
        patterns:
          - "@testing-library/*"
          - "jest*"
          - "cypress*"
          - "@cypress/*"
          - "mocha*"
        update-types:
          - "minor"
          - "patch"
    # Ignore specific packages that might cause compatibility issues
    ignore:
      # Keep webpack stable for OpenShift console plugin compatibility
      - dependency-name: "webpack"
        update-types: ["version-update:semver-major"]
      # Keep React at current major version for stability
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]

  # Monitor GitHub Actions workflows (when added)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"
    reviewers:
      - "alimobrem" 